### ISSUE TITLE
menu sidebar with dropdown link

### ISSUE THREAD

**Issue by felicetto13** [proj-65-team4/DeliverBoo4#29]

**Comment by felicetto13** [comment]
Products
     -Vedi Menu
     -Aggiungi Prodotto
Ordini
     -Vedi Tutti ->id,  n. ordine , data ordine, totale ordine  pulsante per il dettaglio completo
     -Statistiche -> Ammontare vendite (filtro per mese/anno)
                          -> Riepilogo ordini (desc data)

**Comment by Michael-Bombini** [comment]
Products completed Orders  also
